[CI] remove macos install hack for colima (#1594)
* Revert "Fix docker and colima install in CI (#1556)"

This reverts commit a00eaa11375e3946224259cb09ea628b7a3c2480.

* [GHA/io_integration_test] run ci on this branch

* Revert "[GHA/io_integration_test] run ci on this branch"

This reverts commit 57c4c4cbf67f05e8b8cc0faa599e1be59dd71800.

* [ios_integration_test] add continue on error

* [ios_integration_test] properly ignore error

diff --git a/.github/workflows/ios_integration_test.yml b/.github/workflows/ios_integration_test.yml
--- a/.github/workflows/ios_integration_test.yml
+++ b/.github/workflows/ios_integration_test.yml
@@ -94,12 +94,11 @@ jobs:
         run: .flutter/bin/dart run melos yarn-build
 
       - name: Start colima a docker runtime for MacOs
-        # Work around an upstream issue with the runner image:
-        # https://github.com/actions/runner-images/issues/8500
+        # The brew install returns exit code 1 for a non-fatal dependency linker error.
+        # We don't care, the subsequent steps will work still.
         run: |
-          brew upgrade || brew link --overwrite python@3.11
-          brew install docker
-          brew install colima
+          brew install docker || true
+          brew install colima || true
           colima start
 
       - name: Run encointer-node
