[ios_integration_test] properly ignore error

diff --git a/.github/workflows/ios_integration_test.yml b/.github/workflows/ios_integration_test.yml
--- a/.github/workflows/ios_integration_test.yml
+++ b/.github/workflows/ios_integration_test.yml
@@ -94,12 +94,11 @@ jobs:
         run: .flutter/bin/dart run melos yarn-build
 
       - name: Start colima a docker runtime for MacOs
-        # The brew install returns exit code 1 for a non-fatal error.
+        # The brew install returns exit code 1 for a non-fatal dependency linker error.
         # We don't care, the subsequent steps will work still.
-        continue-on-error: true
         run: |
-          brew install docker
-          brew install colima
+          brew install docker || true
+          brew install colima || true
           colima start
 
       - name: Run encointer-node
